// custom imports
import { geistSans, geistMono } from "@/components/fonts";
import ThemeProvider from "@/components/theme-provider";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";

// next standard imports
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Official website of DeepCleanMyMac",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          enableSystem
          disableTransitionOnChange
          defaultTheme="system"
        >
          <NavBar />
          <div className="h-16 invisible"></div>
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
